### ISSUE TITLE
Transacting against a contract fails with js library

### ISSUE THREAD

**Issue by marc4gov** [monax/legacy-contracts.js#89] opened 2017-04-16 12:05 UTC
# Library Issue or Support Request?

This is the place to report any issues with the @monax/legacy-contracts.js JavaScript library.  If you need help with your Solidity code, please see Monax's [Premium Support & Education](https://monax.io/packages/) offering.

# Version Numbers

Fill in version numbers below.

* Node.js: 7.2.0
* Monax CLI: 0.16.0
* @monax/legacy-contracts: 0.16.3

# Issue Description

Getting data from a contract is OK, transacting against a contract fails using the js library. But not when using the `monax pkgs do` command

# Code

Include all code and data needed to reproduce the problem by replacing the examples below.

## Solidity

```Solidity
pragma solidity ^0.4.4;

contract store {
    uint storedData;

    function set(uint x) {
        storedData = x;
    }

    function get() constant returns (uint retVal) {
        return storedData;
    }
}
```

## Monax pkgs do input yaml file

```
jobs:

- name: setStorageBase
  job:
    set:
      val: 5

- name: deployStorageK
  job:
    deploy:
      contract: contracts/storage.sol

- name: setStorage
  job:
    call:
      destination: $deployStorageK
      function: set
      data:
          - $setStorageBase

- name: queryStorage
  job:
    query-contract:
      destination: $deployStorageK
      function: get

- name: assertStorage
  job:
    assert:
      key: $queryStorage
      relation: eq
      val: $setStorageBase

```

## Monax pkgs do output
```
Running TestChain environment setup...
chain_dir: /Users/marc/.monax/chains/testchain
chain_dir_this: /Users/marc/.monax/chains/testchain/testchain_full_000
addr = 4183678EF465F1A32247C29A38A79919DF60FC71

*****Executing Job*****

Job Name                                      defaultAddr

*****Executing Job*****

Job Name                                      setStorageBase

*****Executing Job*****

Job Name                                      deployStorageK
Saving ABI                                    abi/store
Deploying Contract                       name=store
                                         addr=B3FDA8A10E0C09747EB892E2E8F8EB96B71B2E39

*****Executing Job*****

Job Name                                      setStorage

*****Executing Job*****

Job Name                                      queryStorage
Return Value                                  5

*****Executing Job*****

Job Name                                      assertStorage
Assertion Succeeded                           5 == 5
```

### test input
``` 
// store.js
var Blockchain = require('../lib/blockchain.js');
var eriswrapper = require('../lib/eris-wrapper');


function getStorage(address) {
    return new Promise(
        function(resolve, reject) {
            Blockchain.getContract('store', address).get(
                (error, data) => {
                    if (error) {
                        reject(error);
                    } else {
                        resolve(data);
                    }
                });
        });
}

function setStorage(address, num) {
    return new Promise(
        function(resolve, reject) {
            Blockchain.getContract('store', address).set(
                num,
                (error, data) => {
                    if (error) {
                        reject(error);
                    } else {
                        resolve(data);
                    }
                });
        });
}


module.exports = {
    getStorage,
    setStorage,
}

// test.js
const store = require('./store');
const eriswrapper = require('../lib/eris-wrapper');

describe('test', function() {

    it('get storage', function() {
        return store.getStorage(`B3FDA8A10E0C09747EB892E2E8F8EB96B71B2E39`)
                    .then(data => console.log(Number(data)));
    });

    it('set storage', function() {
        return store.setStorage('B3FDA8A10E0C09747EB892E2E8F8EB96B71B2E39',10)
                    .then(data => console.log(data));

    });

});
```

### test output
```
Key:  { address: '4183678EF465F1A32247C29A38A79919DF60FC71',
  pubKey: '79BA0C86814F14DB39F40F5C0FE3D778DA6A0CAE1BB30F0884E18843FE0F8F3D',
  privKey: 'DAECC0A0B1889FDAF843E497C4CD7AA76CB5F4358083C863579A373D802E462479BA0C86814F14DB39F40F5C0FE3D778DA6A0CAE1BB30F0884E18843FE0F8F3D' }


  test
5
    ✓ get storage (88ms)

Burrow error:  Call of method "transactAndHold" with parameters { priv_key: 'DAECC0A0B1889FDAF843E497C4CD7AA76CB5F4358083C863579A373D802E462479BA0C86814F14DB39F40F5C0FE3D778DA6A0CAE1BB30F0884E18843FE0F8F3D',
  address: 'B3FDA8A10E0C09747EB892E2E8F8EB96B71B2E39',
  data: '60fe47b1000000000000000000000000000000000000000000000000000000000000000a',
  gas_limit: 1000000,
  fee: 0 } responded with "Error when transacting: Invalid jump dest".
{ Error: Error when transacting: Invalid jump dest
    at values.next.then (/Users/marc/Blockchain/Projects/BouwChain/api/HerenbouwChain/node_modules/@nodeguy/json-rpc/lib/index.js:16:30)
  method: 'transactAndHold',
  params: 
   [ { priv_key: 'DAECC0A0B1889FDAF843E497C4CD7AA76CB5F4358083C863579A373D802E462479BA0C86814F14DB39F40F5C0FE3D778DA6A0CAE1BB30F0884E18843FE0F8F3D',
       address: 'B3FDA8A10E0C09747EB892E2E8F8EB96B71B2E39',
       data: '60fe47b1000000000000000000000000000000000000000000000000000000000000000a',
       gas_limit: 1000000,
       fee: 0 } ],
  code: -32603,
  message: 'Error when transacting: Invalid jump dest' }
    1) set storage


  1 passing (557ms)
  1 failing

  1) test set storage:
     Error: Error when transacting: Invalid jump dest
      at values.next.then (node_modules/@nodeguy/json-rpc/lib/index.js:16:30)
```

**Comment by NodeGuy** [comment] 2017-04-19 16:41
@marc4gov Thank you for such an elaborate bug report!  All of the information you provided is helpful.

@silasdavis I've recreated this bug and compared the output of `monax pkgs do` vs. legacy-contracts.js.  From what `monax pkgs do` is showing me in verbose mode, they look the same:

```
$ monax pkgs do --chain 89 --address EB972EFE1C7E58C1509DA725C4843A075D326136 --verbose

...

/*
*****Executing Job*****

Job Name                                      setStorage
Type                                          Call
Calling                                  data=60fe47b10000000000000000000000000000000000000000000000000000000000000005
                                  destination=AF9DB34F275F66C3CBD49D8B4DE7A7BBB40A7166
                                     function=set
```

Here's what legacy-contracts.js is sending:

```
 MONAX 59142: { method: 'burrow.transactAndHold',
   params:
    { priv_key: 'F12B17786A37C1B7DB71597E059FD3F8BB301F5645F669B254E4AC19AE508A75CC93B526C7266FBF27F77D2CDCA19E7A03CD2E714E20C0513E36306B84FE0F1F',
      address: 'AF9DB34F275F66C3CBD49D8B4DE7A7BBB40A7166',
      data: '60fe47b10000000000000000000000000000000000000000000000000000000000000005',
      gas_limit: 1000000,
      fee: 0 },
   id: 'W2evW9TmF+zDq1pkwwyJ5qfl+U5rhRMgRZcWUkRe9v0=',
   jsonrpc: '2.0' }
 MONAX 59142: { error:
    { code: -32603,
      message: 'Error when transacting: Invalid jump dest' },
   id: 'W2evW9TmF+zDq1pkwwyJ5qfl+U5rhRMgRZcWUkRe9v0=',
   jsonrpc: '2.0' }
```

This doesn't look like a bug on the JavaScript side.  It would be helpful if `monax pkgs do` could be induced to show the entire transaction so we can compare it instead of just the `data` and `destination` fields but regardless it looks like the JavaScript library is sending the right information to Burrow.

**Comment by silasdavis** [comment] 2017-04-19 17:00
From our slack discussion I recall that Marc did observe that the transactions generated by `monax pkgs do` were non-identical to those produced from the the mis`burrow.transactAndHold` call.

My best guess would be this is some kind of a serialisation/deserialisation issue on one end or the other. Perhaps the address being called doesn't make it through unscathed or the EVM code (data) doesn't.

I should be able to reproduce it from this and find out.

@NodeGuy in your erring example from legacy-contracts.js the params reported there are capture on the JS side I assume. i.e. they are not the returned in the respond from Burrow?

**Comment by NodeGuy** [comment] 2017-04-20 03:23
@silasdavis That's correct, the first object is the JSON-RPC request and the second object is the response.

Here's another test case that fails with the same error—the application from our Getting Started tutorial:  https://github.com/monax/cli/tree/%231332/docs/test/getting-started

**Comment by silasdavis** [comment] 2017-04-20 15:16
The issue seems to be to do with the value being transferred with the call. `monax pkgs do` uses identical `fee` and `amount` leading to a zero value transfer (`value = amount - fee`). The JS libs/Transact end up transferring a value of 1. This leads to branching in the EVM code that leads to an invalid jump destination.

I have captured the traces here:

```
// Working EVM from epm:
MARMOT!: Tx received: &txs.CallTx{Input:(*txs.TxInput)(0xc4208eb5e0), Address:[]uint8{0x16, 0x38, 0xea, 0x7, 0xb9, 0x71, 0xa3, 0xd2, 0x36, 0xf4, 0xaa, 0xa0, 0x79, 0x5b, 0x78, 0x36, 0xe7, 0xe6, 0x6c, 0x17}, GasLimit:1111111111, Fee:9999, Data:[]uint8{0x60, 0xfe, 0x47, 0xb1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x5}}, input: &txs.TxInput{Address:[]uint8{0x45, 0xc4, 0xd1, 0xe3, 0x41, 0x71, 0xcd, 0x17, 0xc5, 0xb7, 0xfe, 0x2, 0xa2, 0xce, 0xcc, 0x96, 0xf9, 0xe8, 0x2e, 0xb}, Amount:9999, Sequence:9, Signature:crypto.SignatureEd25519{0x1d, 0x68, 0x95, 0x62, 0x87, 0xe7, 0x7, 0x15, 0x60, 0xe0, 0xc, 0xbb, 0xc0, 0x64, 0x6e, 0xc2, 0x4a, 0x72, 0xe0, 0x62, 0x64, 0xf1, 0xaa, 0x6e, 0x1d, 0x3b, 0x3, 0x9e, 0x7b, 0x28, 0x5c, 0x5c, 0xfa, 0xfa, 0xa3, 0xdf, 0xee, 0x88, 0x34, 0x75, 0xcb, 0xb, 0xe5, 0x3a, 0xf4, 0x4d, 0x9b, 0x5b, 0x12, 0x75, 0x88, 0xb7, 0x8f, 0x56, 0xbb, 0xab, 0x67, 0xb6, 0x8a, 0xb9, 0xbf, 0xab, 0x93, 0x9}, PubKey:crypto.PubKeyEd25519{0xeb, 0xab, 0xa2, 0x12, 0x76, 0x98, 0xe6, 0x56, 0x60, 0x9b, 0x18, 0x32, 0xd3, 0x89, 0xa3, 0x87, 0x1, 0x47, 0x1d, 0x65, 0xb8, 0x68, 0xab, 0x76, 0x21, 0xaa, 0xf6, 0xc4, 0x97, 0xcc, 0x27, 0x60}} 
INFO[04-20|16:06:54] Account has permission                   module=state address=45C4D1E34171CD17C5B7FE02A2CECC96F9E82E0B perm=call
INFO[04-20|16:06:54] Out account: Account{1638EA07B971A3D236F4AAA0795B7836E7E66C17:<nil> B:0 C:161 S: P:{Base: 100011111110; Set: 11111111111111 []}} module=state
INFO[04-20|16:06:54] Calling contract 0000000000000000000000001638EA07B971A3D236F4AAA0795B7836E7E66C17 with code 60606040526000357C01000000000000000000000000000000000000000000000000000000009004806360FE47B11460435780636D4CE63C14605D57603F565B6002565B34600257605B60048080359060200190919050506082565B005B34600257606C60048050506090565B6040518082815260200191505060405180910390F35B806000600050819055505B50565B60006000600050549050609E565B9056 module=state
INFO[04-20|16:06:54] Code for this contract: 60606040526000357C01000000000000000000000000000000000000000000000000000000009004806360FE47B11460435780636D4CE63C14605D57603F565B6002565B34600257605B60048080359060200190919050506082565B005B34600257606C60048050506090565B6040518082815260200191505060405180910390F35B806000600050819055505B50565B60006000600050549050609E565B9056 module=state
MARMOT!: tx data is: 60FE47B10000000000000000000000000000000000000000000000000000000000000005
MARMOT!: Code: 60606040526000357C01000000000000000000000000000000000000000000000000000000009004806360FE47B11460435780636D4CE63C14605D57603F565B6002565B34600257605B60048080359060200190919050506082565B005B34600257606C60048050506090565B6040518082815260200191505060405180910390F35B806000600050819055505B50565B60006000600050549050609E565B9056
(1) (00000000) 0000000000000000000000001638EA07B971A3D236F4AAA0795B7836E7E66C17 (code=161) gas: 1111111111 (d) 60FE47B10000000000000000000000000000000000000000000000000000000000000005
(pc) 0   (op) PUSH1          (st) 0     => 0x0000000000000000000000000000000000000000000000000000000000000060
(pc) 2   (op) PUSH1          (st) 1     => 0x0000000000000000000000000000000000000000000000000000000000000040
(pc) 4   (op) MSTORE         (st) 2     => 0x0000000000000000000000000000000000000000000000000000000000000060
(pc) 5   (op) PUSH1          (st) 0     => 0x0000000000000000000000000000000000000000000000000000000000000000
(pc) 7   (op) CALLDATALOAD   (st) 1     => 0x60FE47B100000000000000000000000000000000000000000000000000000000
(pc) 8   (op) PUSH29         (st) 1     => 0x0000000100000000000000000000000000000000000000000000000000000000
(pc) 38  (op) SWAP1          (st) 2     => [2] 60FE47B100000000000000000000000000000000000000000000000000000000
(pc) 39  (op) DIV            (st) 2     43871307414348465119245428467174558819278178421933205617286227672654652899328 / 26959946667150639794667015087019630673637144422540572481103610249216 = 1627277233 (0000000000000000000000000000000000000000000000000000000060FE47B1)
(pc) 40  (op) DUP1           (st) 1     => [1] 0x0000000000000000000000000000000000000000000000000000000060FE47B1
(pc) 41  (op) PUSH4          (st) 2     => 0x0000000000000000000000000000000000000000000000000000000060FE47B1
(pc) 46  (op) EQ             (st) 3     0000000000000000000000000000000000000000000000000000000060FE47B1 == 0000000000000000000000000000000000000000000000000000000060FE47B1 = 1
(pc) 47  (op) PUSH1          (st) 2     => 0x0000000000000000000000000000000000000000000000000000000000000043
(pc) 49  (op) JUMPI          (st) 3     ~> 67
(pc) 67  (op) JUMPDEST       (st) 1    
(pc) 68  (op) CALLVALUE      (st) 1     => 0
(pc) 69  (op) PUSH1          (st) 2     => 0x0000000000000000000000000000000000000000000000000000000000000002
(pc) 71  (op) JUMPI          (st) 3     ~> false
(pc) 72  (op) PUSH1          (st) 1     => 0x000000000000000000000000000000000000000000000000000000000000005B
(pc) 74  (op) PUSH1          (st) 2     => 0x0000000000000000000000000000000000000000000000000000000000000004
(pc) 76  (op) DUP1           (st) 3     => [1] 0x0000000000000000000000000000000000000000000000000000000000000004
(pc) 77  (op) DUP1           (st) 4     => [1] 0x0000000000000000000000000000000000000000000000000000000000000004
(pc) 78  (op) CALLDATALOAD   (st) 5     => 0x0000000000000000000000000000000000000000000000000000000000000005
(pc) 79  (op) SWAP1          (st) 5     => [2] 0000000000000000000000000000000000000000000000000000000000000004
(pc) 80  (op) PUSH1          (st) 5     => 0x0000000000000000000000000000000000000000000000000000000000000020
(pc) 82  (op) ADD            (st) 6     32 + 4 = 36 (0000000000000000000000000000000000000000000000000000000000000024)
(pc) 83  (op) SWAP1          (st) 5     => [2] 0000000000000000000000000000000000000000000000000000000000000005
(pc) 84  (op) SWAP2          (st) 5     => [3] 0000000000000000000000000000000000000000000000000000000000000004
(pc) 85  (op) SWAP1          (st) 5     => [2] 0000000000000000000000000000000000000000000000000000000000000024
(pc) 86  (op) POP            (st) 5     => 0x0000000000000000000000000000000000000000000000000000000000000024
(pc) 87  (op) POP            (st) 4     => 0x0000000000000000000000000000000000000000000000000000000000000004
(pc) 88  (op) PUSH1          (st) 3     => 0x0000000000000000000000000000000000000000000000000000000000000082
(pc) 90  (op) JUMP           (st) 4     ~> 130
(pc) 130 (op) JUMPDEST       (st) 3    
(pc) 131 (op) DUP1           (st) 3     => [1] 0x0000000000000000000000000000000000000000000000000000000000000005
(pc) 132 (op) PUSH1          (st) 4     => 0x0000000000000000000000000000000000000000000000000000000000000000
(pc) 134 (op) PUSH1          (st) 5     => 0x0000000000000000000000000000000000000000000000000000000000000000
(pc) 136 (op) POP            (st) 6     => 0x0000000000000000000000000000000000000000000000000000000000000000
(pc) 137 (op) DUP2           (st) 5     => [2] 0x0000000000000000000000000000000000000000000000000000000000000005
(pc) 138 (op) SWAP1          (st) 6     => [2] 0000000000000000000000000000000000000000000000000000000000000000
(pc) 139 (op) SSTORE         (st) 6     {0x0000000000000000000000000000000000000000000000000000000000000000 : 0x0000000000000000000000000000000000000000000000000000000000000005}
(pc) 140 (op) POP            (st) 4     => 0x0000000000000000000000000000000000000000000000000000000000000005
(pc) 141 (op) JUMPDEST       (st) 3    
(pc) 142 (op) POP            (st) 3     => 0x0000000000000000000000000000000000000000000000000000000000000005
(pc) 143 (op) JUMP           (st) 2     ~> 91
(pc) 91  (op) JUMPDEST       (st) 1    
(pc) 92  (op) STOP           (st) 1    INFO[04-20|16:06:54] Successful execution                     module=state


// Broken EVM from JS
MARMOT!: Code: 60606040526000357C01000000000000000000000000000000000000000000000000000000009004806360FE47B11460435780636D4CE63C14605D57603F565B6002565B34600257605B60048080359060200190919050506082565B005B34600257606C60048050506090565B6040518082815260200191505060405180910390F35B806000600050819055505B50565B60006000600050549050609E565B9056

MARMOT!: Tx received: &txs.CallTx{Input:(*txs.TxInput)(0xc4201429b0), Address:[]uint8{0x16, 0x38, 0xea, 0x7, 0xb9, 0x71, 0xa3, 0xd2, 0x36, 0xf4, 0xaa, 0xa0, 0x79, 0x5b, 0x78, 0x36, 0xe7, 0xe6, 0x6c, 0x17}, GasLimit:1111111111, Fee:1, Data:[]uint8{0x60, 0xfe, 0x47, 0xb1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x5}}, input: &txs.TxInput{Address:[]uint8{0x45, 0xc4, 0xd1, 0xe3, 0x41, 0x71, 0xcd, 0x17, 0xc5, 0xb7, 0xfe, 0x2, 0xa2, 0xce, 0xcc, 0x96, 0xf9, 0xe8, 0x2e, 0xb}, Amount:10, Sequence:11, Signature:crypto.SignatureEd25519{0xf0, 0x36, 0x3e, 0x73, 0x94, 0x38, 0x28, 0x82, 0x3f, 0xed, 0xf4, 0xa8, 0x87, 0xdc, 0xcc, 0xc1, 0x16, 0x31, 0x27, 0xea, 0xf, 0xd0, 0x0, 0xda, 0xfc, 0x4, 0x32, 0xc3, 0x21, 0xe7, 0xc0, 0x4d, 0xc5, 0x13, 0x6e, 0xc5, 0x14, 0x4a, 0x34, 0xd0, 0xfe, 0xad, 0x9a, 0x3, 0x64, 0x7a, 0xd0, 0xd3, 0x39, 0x45, 0x2c, 0xd9, 0x37, 0x6, 0xfb, 0xaf, 0x18, 0xbb, 0x89, 0xce, 0x6, 0x2f, 0x1b, 0xe}, PubKey:crypto.PubKeyEd25519{0xeb, 0xab, 0xa2, 0x12, 0x76, 0x98, 0xe6, 0x56, 0x60, 0x9b, 0x18, 0x32, 0xd3, 0x89, 0xa3, 0x87, 0x1, 0x47, 0x1d, 0x65, 0xb8, 0x68, 0xab, 0x76, 0x21, 0xaa, 0xf6, 0xc4, 0x97, 0xcc, 0x27, 0x60}} 
INFO[04-20|16:10:11] Account has permission                   module=state address=45C4D1E34171CD17C5B7FE02A2CECC96F9E82E0B perm=call
INFO[04-20|16:10:11] Out account: Account{1638EA07B971A3D236F4AAA0795B7836E7E66C17:<nil> B:0 C:161 S:FF0ECB0713DB23320850E1348FB3A419732EBC84 P:{Base: 100011111110; Set: 11111111111111 []}} module=state
INFO[04-20|16:10:11] Calling contract 0000000000000000000000001638EA07B971A3D236F4AAA0795B7836E7E66C17 with code 60606040526000357C01000000000000000000000000000000000000000000000000000000009004806360FE47B11460435780636D4CE63C14605D57603F565B6002565B34600257605B60048080359060200190919050506082565B005B34600257606C60048050506090565B6040518082815260200191505060405180910390F35B806000600050819055505B50565B60006000600050549050609E565B9056 module=state
INFO[04-20|16:10:11] Code for this contract: 60606040526000357C01000000000000000000000000000000000000000000000000000000009004806360FE47B11460435780636D4CE63C14605D57603F565B6002565B34600257605B60048080359060200190919050506082565B005B34600257606C60048050506090565B6040518082815260200191505060405180910390F35B806000600050819055505B50565B60006000600050549050609E565B9056 module=state
MARMOT!: tx data is: 60FE47B10000000000000000000000000000000000000000000000000000000000000005
MARMOT!: Code: 60606040526000357C01000000000000000000000000000000000000000000000000000000009004806360FE47B11460435780636D4CE63C14605D57603F565B6002565B34600257605B60048080359060200190919050506082565B005B34600257606C60048050506090565B6040518082815260200191505060405180910390F35B806000600050819055505B50565B60006000600050549050609E565B9056
(1) (00000000) 0000000000000000000000001638EA07B971A3D236F4AAA0795B7836E7E66C17 (code=161) gas: 1111111111 (d) 60FE47B10000000000000000000000000000000000000000000000000000000000000005
(pc) 0   (op) PUSH1          (st) 0     => 0x0000000000000000000000000000000000000000000000000000000000000060
(pc) 2   (op) PUSH1          (st) 1     => 0x0000000000000000000000000000000000000000000000000000000000000040
(pc) 4   (op) MSTORE         (st) 2     => 0x0000000000000000000000000000000000000000000000000000000000000060
(pc) 5   (op) PUSH1          (st) 0     => 0x0000000000000000000000000000000000000000000000000000000000000000
(pc) 7   (op) CALLDATALOAD   (st) 1     => 0x60FE47B100000000000000000000000000000000000000000000000000000000
(pc) 8   (op) PUSH29         (st) 1     => 0x0000000100000000000000000000000000000000000000000000000000000000
(pc) 38  (op) SWAP1          (st) 2     => [2] 60FE47B100000000000000000000000000000000000000000000000000000000
(pc) 39  (op) DIV            (st) 2     43871307414348465119245428467174558819278178421933205617286227672654652899328 / 26959946667150639794667015087019630673637144422540572481103610249216 = 1627277233 (0000000000000000000000000000000000000000000000000000000060FE47B1)
(pc) 40  (op) DUP1           (st) 1     => [1] 0x0000000000000000000000000000000000000000000000000000000060FE47B1
(pc) 41  (op) PUSH4          (st) 2     => 0x0000000000000000000000000000000000000000000000000000000060FE47B1
(pc) 46  (op) EQ             (st) 3     0000000000000000000000000000000000000000000000000000000060FE47B1 == 0000000000000000000000000000000000000000000000000000000060FE47B1 = 1
(pc) 47  (op) PUSH1          (st) 2     => 0x0000000000000000000000000000000000000000000000000000000000000043
(pc) 49  (op) JUMPI          (st) 3     ~> 67
(pc) 67  (op) JUMPDEST       (st) 1    
(pc) 68  (op) CALLVALUE      (st) 1     => 9
(pc) 69  (op) PUSH1          (st) 2     => 0x0000000000000000000000000000000000000000000000000000000000000002
(pc) 71  (op) JUMPI          (st) 3     ~> 2 invalid jump dest PUSH
```

**Comment by silasdavis** [comment] 2017-04-20 15:34
So having checked up on this. The solidity compiler is deliberately throwing and erro (by jumping to the smallest erring location in bytecode, this concept is encapsulated in the [ErrorTag]) if you try to transfer value to a non-payable function. This error trap may not have been included in an earlier compiler. I will do a bit more confirmation and we can see how to best resolve this.

**Comment by silasdavis** [comment] 2017-04-20 18:08
`Transact` in Burrow, for reasons that are a little obscure allows you to set the transaction fee, but not the amount: 

https://github.com/hyperledger/burrow/blob/master/manager/burrow-mint/transactor.go#L182-L190

The amount is hard-coded to '1'. When the `value` transferred by an EVM call is defined as `value = amount - fee`. Monax CLI (`monax pkgs do`) uses an identical amount and fee leading to a zero value transfer. legacy-contract.js uses a fee of '0' leading to a value transfer of '1'. Since the `set` function is not marked 'payable' (see: https://solidity.readthedocs.io/en/develop/miscellaneous.html?highlight=payable#modifiers) the solidity compiler generates EVM code that makes it an error to try to transfer value with a call to the `set` function. Note that earlier solidity compilers may not have generated this error trap, thus this may not have been a problem with an older version of the platform.

By default we should not be transferring value to a contract with a `CallTx`. Since the role of the token is heavily marginalised in Burrow we probably don't lose much by removing this option altogether. We may with to remove the ability to pass in the fee to `Transact`, or we could at least make it possible to pass in the amount and let the caller decide.

For this release I think the most expedient fix is in legacy-contracts.js. @NodeGuy could you please change the default fee to '1', presumably here: https://github.com/monax/legacy-contracts.js/blob/master/lib/utils/config.js#L17 but I think it will also affect your testing.

**Comment by ratranqu** [comment] 2017-04-20 18:13
A side effect to this is that you are “leaking” tokens, so for a system expected to run for a long time, it is a important to get that fixed.

**Comment by silasdavis** [comment] 2017-04-20 18:32
Yes tokens vanish. It's sort of like the heat death, eventually no transactions can be sent. I have a feeling that there is some engineering re-purposing of our natives tokens that could be used for load-balancing or something like that. Certainly we should be conserving the total number, currently the execution engine deducts the fee into oblivion.

It might be worth pushing a patch for this on Burrow that by default does not leak tokens. I'll have a think about this, thanks.

**Comment by test2015deve** [comment] 2017-04-25 04:56
Hi there,

I guess I missed something about solution. Is this problem solved (if then what is the exact solution)
or
Are you working on it? (if then is there any temporary solution)?

Thank you

**Comment by marc4gov** [comment] 2017-04-25 13:50
Why closed? I did a fresh `npm install --save @monax/legacy-contracts` but the issue persists...

**Comment by zramsay** [comment] 2017-04-25 13:53
closed automatically by GitHub in a commit. the CI will push the update soon

**Comment by marc4gov** [comment] 2017-04-26 09:44
When would this be? Still no avail...

**Comment by zramsay** [comment] 2017-04-26 13:52
it's coming - the fix and subsequent testing uncovered a bug

**Comment by zramsay** [comment] 2017-04-30 13:48
this should work with version 0.16.7 now

**Closed by zramsay** 2017-04-30 13:48 UTC

**Comment by EatCodeSleepRepeat** [comment] 2017-05-01 06:29
Confirmed that it works, just tested it with V0.16.7 legacy-contracts. Thanks.
