### ISSUE TITLE
Burrow error:  Call of method "transactAndHold" with parameters

### ISSUE THREAD

**Issue by test2015deve** [monax/legacy-contracts.js#93] opened 2017-04-24 14:22 UTC
# Support Request?

This is the place to report any issues with the @monax/legacy-contracts.js JavaScript library.  If you need help with your Solidity code, please see Monax's [Premium Support & Education](https://monax.io/packages/) offering.

# Version Numbers

Fill in version numbers below.

* Node.js: v7.9.0
* Monax CLI: 0.16.0
* @monax/legacy-contracts: "@monax/legacy-contracts": "0.16.3" 

# Issue Description
I m following the getting started document. Blockchain has been created. I created sample contract and deployed it. But when ı trying to integrate it with the application. Im getting the error as below. Could you help me for solving this?

ERROR: 

Burrow error:  Call of method "transactAndHold" with parameters { priv_key: '37C                                                                                                             E4983B5CDF91D52355820B93931EFF823BD22754FC7DF481D893458B7625FB1FCAEA618C01C052F1                                                                                                             45CB2D8F3F46D79F5673E0EF5BFD7375B9BC7CCFBF1B5',
  address: '5AC80AA2E48DD441FDC3F4E124DBF9170AB25A8B',
  data: '60fe47b1000000000000000000000000000000000000000000000000000000000000002                                                                                                             3',
  gas_limit: 1000000,
  fee: 0 } responded with "Error when transacting: Invalid jump dest".
{ Error: Error when transacting: Invalid jump dest
    at values.next.then (/root/.monax/apps/idi/node_modules/@nodeguy/json-rpc/li                                                                                                             b/index.js:16:30)
  method: 'transactAndHold',
  params:
   [ { priv_key: '37CE4983B5CDF91D52355820B93931EFF823BD22754FC7DF481D893458B762                                                                                                             5FB1FCAEA618C01C052F145CB2D8F3F46D79F5673E0EF5BFD7375B9BC7CCFBF1B5',
       address: '5AC80AA2E48DD441FDC3F4E124DBF9170AB25A8B',
       data: '60fe47b10000000000000000000000000000000000000000000000000000000000                                                                                                             000023',
       gas_limit: 1000000,
       fee: 0 } ],
  code: -32603,
  message: 'Error when transacting: Invalid jump dest' }
(node:8186) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec                                                                                                             tion id: 1): Error: Error when transacting: Invalid jump dest
(node:8186) DeprecationWarning: Unhandled promise rejections are deprecated. In                                                                                                              the future, promise rejections that are not handled will terminate the Node.js p                                                                                                             rocess with a non-zero exit code.

# Code

All my code as below. I created them by using getting started documentation

## Solidity

```Solidity
contract IdisContractsFTW {
  uint storedData;

  function set(uint x) {
    storedData = x;
  }

  function get() constant returns (uint retVal) {
    return storedData;
  }
}
```

## JavaScript

```JavaScript
// requires
var fs = require ('fs');
var prompt = require('prompt');
var erisC = require('@monax/legacy-contracts');
var accountData = require('./accounts.json');
var contractData = require('./jobs_output.json');

var erisdbURL = "http://localhost:1337/rpc";

var idisContractAddress = contractData["deployStorageK"];
var idisAbi = JSON.parse(fs.readFileSync("./abi/" + idisContractAddress));
var contractsManager = erisC.newContractManagerDev(erisdbURL, accountData.testchain_full_000);
var idisContract = contractsManager.newContractFactory(idisAbi).at(idisContractAddress);

function getValue(callback) {
    idisContract.get(function(error, result){
        if (error) { throw error }
        console.log("Idi's number is:\t\t\t" + result.toNumber());
        callback();
    });
}

function changeValue() {
    prompt.message = "What number should Idi make it?";
    prompt.delimiter = "\t";
    prompt.start();
    prompt.get(['value'], function (error, result) {
        if (error) { throw error }
        setValue(result.value)
    });
}

function setValue(value) {
    idisContract.set(value, function(error, result){
        if (error) { throw error }
        getValue(function(){});
    });
}

// run
getValue(changeValue);

**Comment by NodeGuy** [comment] 2017-04-25 03:09
Thank you, this is a duplicate of #89.

**Closed by NodeGuy** 2017-04-25 03:09 UTC
